INSERT INTO Breed (breed, species)
Values
('Boykin Spaniel','Dog'),
('Finnish Spitz','Dog'),
('Manchester Terrier','Dog'),
('Schnoodle','Dog'),
('Afghan Hound','Dog'),
('Bracco Italiano','Dog'),
('Flat-Coated Retriever','Dog'),
('Mastiff','Dog'),
('Scottish Deerhound','Dog'),
('Airedale Terrier','Dog'),
('Briard','Dog'),
('Fox Terrier','Dog'),
('Miniature American Shepherd','Dog'),
('Scottish Terrier','Dog'),
('Akbash Dog','Dog'),
('Brittany','Dog'),
('French Bulldog','Dog'),
('Miniature Bull Terrier','Dog'),
('Sealyham Terrier','Dog'),
('Akita','Dog'),
('Brussels Griffon','Dog'),
('German Pinscher','Dog'),
('Miniature Pinscher','Dog'),
('Shetland Sheepdog','Dog'),
('Alapaha Blue Blood Bulldog','Dog'),
('Bull Terrier','Dog'),
('German Shepherd Dog','Dog'),
('Miniature Schnauzer','Dog'),
('Shiba Inu','Dog'),
('Alaskan Husky','Dog'),
('Bulldog','Dog'),
('German Shorthaired Pointer','Dog'),
('Mudi','Dog'),
('Shih Tzu','Dog'),
('Alaskan Malamute','Dog'),
('Bullmastiff','Dog'),
('German Spitz','Dog'),
('Neapolitan Mastiff','Dog'),
('Shihpoo','Dog'),
('American Bulldog','Dog'),
('Cairn Terrier','Dog'),
('German Wirehaired Pointer','Dog'),
('Newfoundland','Dog'),
('Siberian Husky','Dog'),
('American Eskimo','Dog'),
('Canaan Dog','Dog'),
('Giant Schnauzer','Dog'),
('Norfolk Terrier','Dog'),
('Silken Windhound','Dog'),
('American Foxhound','Dog'),
('Cane Corso','Dog'),
('Glen of Imaal Terrier','Dog'),
('Norwegian Buhund','Dog'),
('Silky Terrier','Dog'),
('American Pit Bull Terrier','Dog'),
('Cardigan Welsh Corgi','Dog'),
('Golden Retriever','Dog'),
('Norwegian Elkhound','Dog'),
('Skye Terrier','Dog'),
('American Staffordshire Terrier','Dog'),
('Catahoula Leopard Dog','Dog'),
('Goldendoodle','Dog'),
('Norwegian Lundehund','Dog'),
('Sloughi','Dog'),
('American Water Spaniel','Dog'),
('Caucasian Ovcharka','Dog'),
('Gordon Setter','Dog'),
('Norwich Terrier','Dog'),
('Small Munsterlander Pointer','Dog'),
('Anatolian Shepherd Dog','Dog'),
('Cavalier King Charles Spaniel','Dog'),
('Great Dane','Dog'),
('Nova Scotia Duck Tolling Retriever','Dog'),
('Soft Coated Wheaten Terrier','Dog'),
('Aussiedoodle','Dog'),
('Cavapom','Dog'),
('Great Pyrenees','Dog'),
('Old English Sheepdog','Dog'),
('Spanish Greyhound','Dog'),
('Australian Cattle Dog','Dog'),
('Cavapoo','Dog'),
('Greater Swiss Mountain Dog','Dog'),
('Otterhound','Dog'),
('Spanish Water Dog','Dog'),
('Australian Kelpie','Dog'),
('Cesky Terrier','Dog'),
('Greyhound','Dog'),
('Papillon','Dog'),
('Spinone Italiano','Dog'),
('Australian Shepherd','Dog'),
('Chart Polski','Dog'),
('Harrier','Dog'),
('Pekeapoo','Dog'),
('Sprollie','Dog'),
('Australian Terrier','Dog'),
('Chesapeake Bay Retriever','Dog'),
('Havanese','Dog'),
('Pekingese','Dog'),
('Staffordshire Bull Terrier','Dog'),
('Azawakh','Dog'),
('Chihuahua','Dog'),
('Ibizan Hound','Dog'),
('Pembroke Welsh Corgi','Dog'),
('Standard Schnauzer','Dog'),
('Basador','Dog'),
('Chinese Crested','Dog'),
('Icelandic Sheepdog','Dog'),
('Perro de Presa Canario','Dog'),
('Sussex Spaniel','Dog'),
('Basenji','Dog'),
('Chinese Shar-Pei','Dog'),
('Irish Red and White Setter','Dog'),
('Peruvian Inca Orchid','Dog'),
('Swedish Lapphund','Dog'),
('Basset Bleu de Gascogne','Dog'),
('Chinook','Dog'),
('Irish Setter','Dog'),
('Petit Basset Griffon Vendeen','Dog'),
('Swedish Vallhund','Dog'),
('Basset Hound','Dog'),
('Chow Chow','Dog'),
('Irish Terrier','Dog'),
('Pharaoh Hound','Dog'),
('Thai Ridgeback','Dog'),
('Beagle','Dog'),
('Chug','Dog'),
('Irish Water Spaniel','Dog'),
('Plott','Dog'),
('Tibetan Mastiff','Dog'),
('Bearded Collie','Dog'),
("Cirneco dell'Etna",'Dog'),
('Irish Wolfhound','Dog'),
('Pointer','Dog'),
('Tibetan Spaniel','Dog'),
('Beauceron','Dog'),
('Clumber Spaniel','Dog'),
('Italian Greyhound','Dog'),
('Polish Lowland Sheepdog','Dog'),
('Tibetan Terrier','Dog'),
('Bedlington Terrier','Dog'),
('Cockapoo','Dog'),
('Jack Russell Terrier','Dog'),
('Pomapoo','Dog'),
('Tosa Ken','Dog'),
('Belgian Laekenois','Dog'),
('Cocker Spaniel','Dog'),
('Japanese Chin','Dog'),
('Pomeranian','Dog'),
('Toy Fox Terrier','Dog'),
('Belgian Malinois','Dog'),
('Collie','Dog'),
('Keeshond','Dog'),
('Pomsky','Dog'),
('Toy Poodle','Dog'),
('Belgian Sheepdog','Dog'),
('Coton de Tulear','Dog'),
('Kerry Blue Terrier','Dog'),
('Poodle','Dog'),
('Treeing Walker Coonhound','Dog'),
('Belgian Tervuren','Dog'),
('Curly-Coated Retriever','Dog'),
('Komondor','Dog'),
('Portuguese Podengo','Dog'),
('Vizsla','Dog'),
('Bergamasco','Dog'),
('Dachshund','Dog'),
('Kooikerhondje','Dog'),
('Portuguese Water Dog','Dog'),
('Volpino Italiano','Dog'),
('Berger Picard','Dog'),
('Dalmatian','Dog'),
('Kromfohrlander','Dog'),
('Pug','Dog'),
('Weimaraner','Dog'),
('Bernese Mountain Dog','Dog'),
('Dandie Dinmont Terrier','Dog'),
('Kuvasz','Dog'),
('Pugapoo','Dog'),
('Welsh Springer Spaniel','Dog'),
('Bichon Frise','Dog'),
('Doberman Pinscher','Dog'),
('Labradoodle','Dog'),
('Puggle','Dog'),
('Welsh Terrier','Dog'),
('Black and Tan Coonhound','Dog'),
('Dogo Argentino','Dog'),
('Labrador Retriever','Dog'),
('Puli','Dog'),
('West Highland White Terrier','Dog'),
('Black Russian Terrier','Dog'),
('Dogue de Bordeaux','Dog'),
('Lacy Dog','Dog'),
('Pumi','Dog'),
('Whippet','Dog'),
('Bloodhound','Dog'),
('Doxiepoo','Dog'),
('Lagotto Romagnolo','Dog'),
('Pyrenean Shepherd','Dog'),
('Wirehaired Pointing Griffon','Dog'),
('Blue Picardy Spaniel','Dog'),
('English Cocker Spaniel','Dog'),
('Lakeland Terrier','Dog'),
('Rat Terrier','Dog'),
('Wirehaired Vizsla','Dog'),
('Bluetick Coonhound','Dog'),
('English Foxhound','Dog'),
('Large Munsterlander','Dog'),
('Redbone Coonhound','Dog'),
('Xoloitzcuintli','Dog'),
('Boerboel','Dog'),
('English Setter','Dog'),
('Leonberger','Dog'),
('Rhodesian Ridgeback','Dog'),
('Yorkipoo','Dog'),
('Bolognese','Dog'),
('English Springer Spaniel','Dog'),
('Lhasa Apso','Dog'),
('Rottweiler','Dog'),
('Yorkshire Terrier','Dog'),
('Border Collie','Dog'),
('English Toy Spaniel','Dog'),
('Lhasapoo','Dog'),
('Russian Toy','Dog'),
('Mixed','Dog'),
('Border Terrier','Dog'),
('Entlebucher Mountain Dog','Dog'),
('Longdog','Dog'),
('Saint Bernard','Dog'),
('Unknown','Dog'),
('Borzoi','Dog'),
('Eurasier','Dog'),
('Lowchen','Dog'),
('Saluki','Dog'),
('Boston Terrier','Dog'),
('Field Spaniel','Dog'),
('Lurcher','Dog'),
('Samoyed','Dog'),
('Bouvier des Flandres','Dog'),
('Fila Brasileiro','Dog'),
('Maltese','Dog'),
('Schapendoes','Dog'),
('Boxer','Dog'),
('Finnish Lapphund','Dog'),
('Maltipoo','Dog'),
('Schipperke','Dog'),
('Unknown','Cat'),
('Mixed','Cat'),
('Abyssinian','Cat'),
('Chartreux','Cat'),
('LaPerm','Cat'),
('Scottish Fold','Cat'),
('Aegean Cat','Cat'),
('Cornish Rex','Cat'),
('Li Hua','Cat'),
('Selkirk Rex','Cat'),
('American Bobtail','Cat'),
('Cymric','Cat'),
('Maine Coon','Cat'),
('Siamese','Cat'),
('American Curl','Cat'),
('Devon Rex','Cat'),
('Manx','Cat'),
('Siberian','Cat'),
('American Shorthair','Cat'),
('Egyptian Mau','Cat'),
('Munchkin','Cat'),
('Singapura','Cat'),
('American Wirehair','Cat'),
('Exotic Shorthair','Cat'),
('Norwegian Forest Cat','Cat'),
('Somali','Cat'),
('Balinese','Cat'),
('Havana Brown','Cat'),
('Ocicat','Cat'),
('Sphynx','Cat'),
('Bengal','Cat'),
('Himalayan','Cat'),
('Oriental','Cat'),
('Tonkinese','Cat'),
('Birman','Cat'),
('Japanese Bobtail','Cat'),
('Persian','Cat'),
('Toyger','Cat'),
('Bombay','Cat'),
('Javanese','Cat'),
('Pixiebob','Cat'),
('Turkish Angora','Cat'),
('British Shorthair','Cat'),
('Korat','Cat'),
('Ragamuffin','Cat'),
('Turkish Van','Cat'),
('Burmese','Cat'),
('Kurilian Bobtail','Cat'),
('Russian Blue','Cat'),
('Burmilla','Cat'),
('Ragdoll','Cat'),
('Savannah','Cat');
